kind: ClusterRole
metadata:
  name: acme-controller
rules:
- apiGroups:
  - "route.openshift.io"
  resources:
  - routes
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete

- apiGroups:
  - "route.openshift.io"
  resources:
  - routes/custom-host
  verbs:
  - create

- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create

- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete

- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
